# Generated by Django 5.2.6 on 2026-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoventa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
