# Generated by Django 5.2.6 on 2025-12-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='origen_id',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='origen_tipo',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20),
        ),
    ]
