# Generated by Django 5.2.6 on 2026-01-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_movimientoinventario_origen_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientoinventariodetalle',
            unique_together={('movimiento', 'producto')},
        ),
    ]
