# Generated by Django 5.2.6 on 2025-11-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='negocio.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Cerrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='monto_final_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='monto_final_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
