# Generated by Django 5.2.6 on 2025-11-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_arqueocaja_sucursal_alter_arqueocaja_diferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='Cerrado', max_length=20),
        ),
    ]
