# Generated by Django 5.2.6 on 2025-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_arqueocaja_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='CERRADA', max_length=20),
        ),
    ]
