# Generated by Django 5.2.6 on 2026-01-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_arqueocaja_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10),
        ),
    ]
