# Generated by Django 5.2.6 on 2025-11-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='punto_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='negocio.puntoventa'),
            preserve_default=False,
        ),
    ]
